spring:
  application:
    name: perfume-stalker-api

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500, expireAfterWrite=24h

  mvc:
    async:
      request-timeout: 60000

server:
  port: 8080
  shutdown: graceful

notion:
  api:
    url: "https://api.notion.com/v1"
    version: "2026-03-11"
    token: ${NOTION_TOKEN}
  db:
    master-id: ${NOTION_MASTER_DB_ID}
    master-data-source-id: ${NOTION_MASTER_DATA_SOURCE_ID}
    usage-log-id: ${NOTION_USAGE_LOG_DB_ID}
    usage-log-data-source-id: ${NOTION_USAGE_LOG_DATA_SOURCE_ID}
    user-id : ${NOTION_USER_DB_ID}
    user-data-source-id : ${NOTION_USER_DATA_SOURCE_ID}

logging:
  level:
    root: INFO
    com.perfumestalker: DEBUG
    # WebClient 통신 시 노션 API 에러나면 아래 줄 주석 풀고 디버깅
    # org.springframework.web.reactive.client: DEBUG

openweathermap:
  api-key: ${OPENWEATHER_API_KEY}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:259200000} # 기본값 72시간 세팅

# ngrok http 8080